### PR TITLE
Fix a memory leak in repeated AWS4Auth initializations

### PR DESCRIPTION
**Pull request by miikka**
This PR fixes the issue #67. Before the change creating `AWS4Auth` instances with `security_token` set would add one entry per instance to `default_include_headers`. This PR fixes it by always copying the list before modifying it.

### CODE REVIEW

**Comment by Colin-b** [comment]
Hello @miikka 

Thanks for the proposal. Looking at the code I think a more elegant solution would be to address the TODO in the code base in the first place. This variable should indeed not be shared accross instances. And in addition it might make more sense to use a set here. I will take care of this during the weekend.

Thanks again

**Comment by miikka** [comment]
Makes sense. In this PR, I tried to do the minimal change to address the issue, but addressing both TODOs properly would certainly be better. Looking forward to your solution.

**Comment by marioluan** [comment]
> Hello @miikka
> 
> Thanks for the proposal. Looking at the code I think a more elegant solution would be to address the TODO in the code base in the first place. This variable should indeed not be shared accross instances. And in addition it might make more sense to use a set here. I will take care of this during the weekend.
> 
> Thanks again

Any progress here?

**Comment by Colin-b** [comment]
For now I am focusing on improving the test suite so that we can work on proper async support. Once test suite is ready however I  plan on tackling those "quick" win.

**Comment by Colin-b** [comment]
Thanks again for the proposal, I will merge and update to properly address todo

**Comment by Colin-b** [comment]
Release 0.20.0 is now available on pypi with this fix (amongst others).

**Pull request merged**
