### PR TITLE
Add support for AWS authentication

### PR DESCRIPTION
**Pull request by martinka**
… due to api changes in AWS since request_aws4auth was updated.  I am still working on updating the live tests. And trying to get access to the AWS signing test suite which seems to have been moved, or taken down.  I have not used pytest before and the code in requests-aws4auth which this is based on uses unittest.    I wanted to get you to look at this so if we want to make changes to make it more consistent you might be able to point me in the correct direction. 

One specific area I could use help with is the live tests basically run through a bunch of tests cases in one test.  the unittest framework will run all of them even if some fail pytest seems to stop on the first one.  I am wondering if there is a way to change that behavior ( or a different way of parameterizing the test to get that result.). 

Also if there are other changes you would like me to make aka style etc. let me know.  Again this is largely a port of the requests-aws4auth over.      

Please feel free to let me know what you think.

### CODE REVIEW

**Comment by martinka** [comment]
Both your project and the requests-aws4auth project use MIT license so I think we should be ok on that front.

**Comment by martinka** [comment]
I will update the tests to remove the user agent header which should fix the build issue.

**Comment by Colin-b** [comment]
Thanks a lot, that's a lot to digest so if you don't mind I will try to find some time somewhere next week if that's ok ?  Also I think it would be best to only provide the Auth class you will actually need (but I might be wrong, I'll give it a deeper look)

**Comment by martinka** [comment]
Yep its a lot, next week is fine.  Also the original code I am basing it on is here: https://github.com/sam-washington/requests-aws4auth ...  I think most of the classes are required, but it could be rewritten depending on what we want to do.

**Comment by martinka** [comment]
I am working on getting coverage to 100% but have hit a bit of a snag..  pytest indicates that lines 624-629 in are not covered.. however two tests which are passing test+amz_date_warning and test_amz_date cover this code.   not sure if this is some weird interaction with the warnings.catch_warnings and code coverage or what.  I will try to dig into it but thought since you are more familiar with pytest you might know whats going on.

**Comment by martinka** [comment]
I am close to 100% test coverage. .However I don't think lines 239 or 240 are reachable without something going wrong in a way I cannot force to happen.  I can remove the try/except since I can't think of how it could be triggered.. but that is assuming there isn't a whole in the date parsing regular expresions.  I think that is the only code currently not covered by a unit test.

**Comment by Colin-b** [comment]
Thx, I will try to take a look at this tomorrow evening :-)

**Comment by martinka** [comment]
I resolved the test coverage.

**Comment by Colin-b** [comment]
Apologies for not reviewing yet, I will invest time to dive into this and hopefully issue a new release this week end :)

**Comment by Colin-b** [comment]
Thanks a lot !

**Comment by Colin-b** [comment]
@martinka I will update the code a bit before pushing a new release, I will also have a look at AWS documentation and update the documentation of httpx_auth to advertise this new class :)

**Comment by martinka** [comment]
Thanks for including it.   Let me know there are any issues with it.

**Comment by Colin-b** [comment]
Hi @martinka 

I am still refactoring it, the main idea would be to make sure that the same authentication class can be used across many requests and to keep the code as straightforward as possible.

I will also update the test cases to check the HTTP queries that are sent instead of checking function returns but overall your work is great, thanks a lot and I will keep you posted (I will continue to work on this tomorrow evening and will give you a status if there is still no release at this point)

**Comment by martinka** [comment]
Great.. let me know if you need me to do anything.  Happy to help.

**Comment by Colin-b** [comment]
I am still migrating the test cases to pytest but it's almost there :)

Then from where I stand there will be 4 remaining points:

1. Check if we need to expose the ability to change the list of headers to use in computing the signature (I would rather go live with a limited set of features rather than having to maintain a list of features that may not make sense, KISS rule applied here)
2. Document this new authentication class
3. Subclassing this class to provide a class already handling s3 requests (it will ease support for other service specific amazon auth)
4. Check if we can download the AWS test suite at test runtime

I am working on the feature/aws branch, so if you want to tackle any of those points feel free, anyway I will continue tomorrow :)

**Comment by martinka** [comment]
I will take a look, I also have a request into amazon to get access to the test suite, I will follow up on that. I can also look at the documentation.

**Comment by martinka** [comment]
I just got feedback from my AWS contact and it seems like the test suite is no longer being made public.  still pushing on them but it seems unlikely to be going anywhere.

**Pull request merged**
